[install]
minimumReleaseAge = 1209600 # 14 days
minimumReleaseAgeExcludes = [
  "@agentclientprotocol/sdk",
  "@remix-run/route-pattern",
  "acp-client",
  "ai-sdk-json-schema",
  "electrobun",
  "powerkeys",
  "preact-sigma",
  "procband",
  "radashi",
  "rouzer",

  # Turbo
  "turbo",
  "@turbo/darwin-64",
  "@turbo/darwin-arm64",
  "@turbo/linux-64",
  "@turbo/linux-arm64",
  "@turbo/windows-64",
  "@turbo/windows-arm64",

  # TSRX
  "@tsrx/bun-plugin-preact",
  "@tsrx/core",
  "@tsrx/eslint-parser",
  "@tsrx/eslint-plugin",
  "@tsrx/preact",
  "@tsrx/prettier-plugin",
  "@tsrx/typescript-plugin",
  "@tsrx/vite-plugin-preact",
  "esrap",
]
