[install]
minimumReleaseAge = 1209600 # 14 days
minimumReleaseAgeExcludes = [
  "@clack/core",
  "@clack/prompts",
  "electrobun",
  "powerkeys",
  "preact-sigma",
  "radashi",

  # TSRX
  "@tsrx/bun-plugin-preact",
  "@tsrx/core",
  "@tsrx/eslint-parser",
  "@tsrx/eslint-plugin",
  "@tsrx/preact",
  "@tsrx/prettier-plugin",
  "@tsrx/typescript-plugin",
  "@tsrx/vite-plugin-preact",
  "esrap",
]
