import { css } from "@goddard-ai/styled-system/css"
import { token } from "@goddard-ai/styled-system/tokens"

export default {
  field: css({
    display: "grid",
    gap: "5px",
    minWidth: "0",
    '&[data-compact="true"]': {
      width: "fit-content",
      maxWidth: "100%",
    },
  }),
  label: css({
    color: "muted",
    fontSize: "0.76rem",
    fontWeight: "650",
    lineHeight: "1.2",
  }),
  tooltipTrigger: css({
    display: "block",
    minWidth: "0",
    maxWidth: "100%",
  }),
  trigger: css({
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "6px",
    width: "100%",
    minHeight: "36px",
    paddingInline: "10px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "background",
    color: "text",
    cursor: "pointer",
    textAlign: "left",
    outline: "none",
    transition: "color 160ms cubic-bezier(0.23, 1, 0.32, 1)",
    _hover: {
      borderColor: "accent",
    },
    _focusVisible: {
      borderColor: "accentStrong",
      boxShadow: `0 0 0 3px color-mix(in srgb, ${token.var("colors.accent")} 18%, transparent)`,
    },
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.5",
    },
    '&[data-compact="true"]': {
      width: "auto",
      maxWidth: "100%",
      minHeight: "28px",
      paddingInline: "0",
      border: "none",
      backgroundColor: "transparent",
      _hover: {
        color: "accentStrong",
      },
    },
  }),
  triggerContent: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "7px",
    minWidth: "0",
    maxWidth: "100%",
  }),
  triggerLabel: css({
    minWidth: "0",
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "0.88rem",
    fontWeight: "600",
    '[data-compact="true"] &': {
      fontSize: "0.8rem",
    },
  }),
  itemIcon: css({
    width: "16px",
    height: "16px",
    flexShrink: "0",
    borderRadius: "4px",
    color: "inherit",
    "[data-theme=dark] &": {
      color: "white",
    },
  }),
  agentItemIcon: css({
    width: "14px",
    height: "14px",
    flexShrink: "0",
    borderRadius: "4px",
    color: "inherit",
    "[data-theme=dark] &": {
      color: "white",
    },
  }),
  triggerPlaceholder: css({
    color: "muted",
    fontWeight: "500",
  }),
  chevron: css({
    flexShrink: "0",
    transition: "transform 160ms cubic-bezier(0.23, 1, 0.32, 1)",
  }),
  tooltipContent: css({
    display: "grid",
    gap: "4px",
    alignItems: "start",
  }),
  tooltipShortcut: css({
    color: "muted",
    fontSize: "0.72rem",
    fontWeight: "560",
    lineHeight: "1.2",
  }),
  menu: css({
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    width: "min(360px, var(--available-width))",
    minWidth: "min(280px, var(--available-width))",
    maxWidth: "var(--available-width)",
    maxHeight: "min(360px, var(--available-height))",
    overflow: "hidden",
    border: "1px solid {colors.border}",
    borderRadius: "10px",
    backgroundColor: "panel",
    outline: "none",
  }),
  menuBody: css({
    display: "contents",
  }),
  menuFilter: css({
    width: "100%",
    padding: "10px 12px 8px",
    border: "none",
    borderBottom: "1px solid {colors.border}",
    backgroundColor: "transparent",
    color: "text",
    fontSize: "0.84rem",
    outline: "none",
    _placeholder: {
      color: "muted",
    },
    _focusVisible: {
      borderBottomColor: "accentStrong",
    },
  }),
  menuList: css({
    display: "grid",
    gap: "0",
    minHeight: "0",
    margin: "0",
    padding: "0",
    overflowY: "auto",
    listStyle: "none",
  }),
  menuButton: css({
    position: "relative",
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    width: "100%",
    minHeight: "34px",
    paddingBlock: "7px",
    paddingInline: "10px",
    border: "none",
    backgroundColor: "transparent",
    color: "text",
    cursor: "pointer",
    fontSize: "0.86rem",
    fontWeight: "560",
    outline: "none",
    textAlign: "left",
    transition: "background-color 120ms ease",
    _hover: {
      backgroundColor: "surface",
    },
    _focusVisible: {
      _after: {
        content: '""',
        position: "absolute",
        inset: "2px",
        borderRadius: "8px",
        border: "2px solid {colors.accentStrong}",
        pointerEvents: "none",
      },
    },
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.5",
    },
  }),
  menuButtonText: css({
    display: "grid",
    gap: "3px",
    minWidth: "0",
  }),
  menuButtonLabel: css({
    minWidth: "0",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    lineHeight: "1.35",
  }),
  menuButtonDetail: css({
    minWidth: "0",
    color: "muted",
    fontSize: "0.76rem",
    fontWeight: "480",
    lineHeight: "1.35",
  }),
  menuButtonActive: css({
    backgroundColor: "surface",
  }),
  menuEmpty: css({
    display: "grid",
    placeItems: "center",
    minHeight: "64px",
    color: "muted",
    fontSize: "0.82rem",
    textAlign: "center",
  }),
}
