import { css } from "@goddard-ai/styled-system/css"

export default {
  page: css({
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    gap: "16px",
    height: "100%",
    padding: "18px",
  }),
  header: css({
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "end",
    gap: "16px",
    paddingBlockEnd: "14px",
    borderBottom: "1px solid {colors.border}",
    "@media (max-width: 760px)": {
      gridTemplateColumns: "1fr",
      alignItems: "start",
    },
  }),
  headingGroup: css({
    display: "grid",
    gap: "6px",
    minWidth: "0",
  }),
  eyebrow: css({
    color: "accentStrong",
    fontSize: "0.72rem",
    fontWeight: "740",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  }),
  title: css({
    margin: "0",
    color: "text",
    fontSize: "1.18rem",
    fontWeight: "760",
    lineHeight: "1.2",
  }),
  body: css({
    maxWidth: "78ch",
    margin: "0",
    color: "muted",
    fontSize: "0.88rem",
    lineHeight: "1.55",
  }),
  statRow: css({
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: "8px",
    "@media (max-width: 760px)": {
      justifyContent: "flex-start",
    },
  }),
  stat: css({
    display: "inline-flex",
    alignItems: "center",
    minHeight: "28px",
    paddingInline: "9px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "surface",
    color: "text",
    fontSize: "0.76rem",
    fontWeight: "700",
  }),
  canvas: css({
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr) auto",
    minHeight: "0",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "background",
    overflow: "hidden",
  }),
  inboxFrame: css({
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    minHeight: "0",
  }),
  selectedPanel: css({
    display: "grid",
    gap: "4px",
    padding: "10px 14px",
    borderTop: "1px solid {colors.border}",
    backgroundColor: "surface",
  }),
  selectedTitle: css({
    margin: "0",
    color: "text",
    fontSize: "0.82rem",
    fontWeight: "720",
  }),
  selectedBody: css({
    margin: "0",
    color: "muted",
    fontFamily: '"IBM Plex Mono", "SFMono-Regular", "Menlo", monospace',
    fontSize: "0.74rem",
    overflowWrap: "anywhere",
  }),
}
