import type { InboxItem } from "@goddard-ai/inbox/schema"

/** Stable fake inbox rows used by the inbox debug surface. */
export const INBOX_DEBUG_ITEMS = [
  {
    id: "inb_debug_blocked_session",
    entityId: "ses_debug_blocked",
    reason: "session.blocked",
    status: "unread",
    priority: "normal",
    updatedAt: Date.UTC(2026, 0, 10, 11, 57),
    readAt: null,
    scope: "Review sync daemon",
    headline: "Needs a decision on the GitHub webhook replay strategy.",
    turnId: "turn_debug_blocked",
  },
  {
    id: "inb_debug_read_session",
    entityId: "ses_debug_read",
    reason: "session.turn_ended",
    status: "read",
    priority: "normal",
    updatedAt: Date.UTC(2026, 0, 10, 11, 44),
    readAt: Date.UTC(2026, 0, 10, 11, 45),
    scope: "Inbox UI",
    headline: "Rendered the main tab view with local search and filters.",
    turnId: "turn_debug_read",
  },
  {
    id: "inb_debug_saved_pr",
    entityId: "pr_debug_saved",
    reason: "pull_request.updated",
    status: "saved",
    priority: "low",
    updatedAt: Date.UTC(2026, 0, 10, 10, 28),
    readAt: Date.UTC(2026, 0, 10, 10, 29),
    scope: "goddard-ai #128",
    headline: "Saved until the pull request fixture screen has enough metadata.",
    turnId: null,
  },
  {
    id: "inb_debug_replied_session",
    entityId: "ses_debug_replied",
    reason: "session.blocked",
    status: "replied",
    priority: "normal",
    updatedAt: Date.UTC(2026, 0, 9, 20, 12),
    readAt: Date.UTC(2026, 0, 9, 20, 16),
    scope: "Terminal polish",
    headline: "User replied with the exact resize behavior to preserve.",
    turnId: "turn_debug_replied",
  },
  {
    id: "inb_debug_completed_session",
    entityId: "ses_debug_completed",
    reason: "session.turn_ended",
    status: "completed",
    priority: "low",
    updatedAt: Date.UTC(2026, 0, 8, 15, 6),
    readAt: Date.UTC(2026, 0, 8, 15, 8),
    scope: "Session list",
    headline: "Completed after validating title search and tab opening.",
    turnId: "turn_debug_completed",
  },
  {
    id: "inb_debug_archived_pr",
    entityId: "pr_debug_archived",
    reason: "pull_request.created",
    status: "archived",
    priority: "normal",
    updatedAt: Date.UTC(2026, 0, 2, 9, 41),
    readAt: Date.UTC(2026, 0, 2, 9, 44),
    scope: "goddard-ai #117",
    headline: "Archived after the linked review was superseded.",
    turnId: null,
  },
] satisfies InboxItem[]
