import { css } from "@goddard-ai/styled-system/css"

export default {
  root: css({
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minWidth: "0",
  }),
  toolbar: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    minHeight: "58px",
    paddingInline: "16px",
    paddingBlock: "10px",
    borderBottom: "1px solid {colors.border}",
    "@media (max-width: 860px)": {
      alignItems: "stretch",
      flexDirection: "column",
    },
  }),
  headingGroup: css({
    display: "flex",
    alignItems: "center",
    gap: "14px",
    minWidth: "0",
    "@media (max-width: 640px)": {
      alignItems: "stretch",
      flexDirection: "column",
      gap: "10px",
    },
  }),
  heading: css({
    margin: "0",
    color: "text",
    fontSize: "1rem",
    fontWeight: "720",
    lineHeight: "1.2",
  }),
  filterGroup: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "2px",
    minWidth: "0",
    padding: "2px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "surface",
    overflowX: "auto",
  }),
  filterButton: css({
    flexShrink: "0",
    minHeight: "28px",
    paddingInline: "10px",
    paddingBlock: "0",
    border: "1px solid transparent",
    borderRadius: "6px",
    backgroundColor: "transparent",
    color: "muted",
    fontSize: "0.8rem",
    fontWeight: "650",
    cursor: "pointer",
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "2px",
    },
    "&[data-selected='true']": {
      borderColor: "border",
      backgroundColor: "background",
      color: "text",
      boxShadow: "0 1px 2px rgba(77, 91, 109, 0.14)",
    },
  }),
  toolbarControls: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "8px",
    minWidth: "280px",
    "@media (max-width: 860px)": {
      justifyContent: "stretch",
      minWidth: "0",
    },
  }),
  searchField: css({
    display: "flex",
    alignItems: "center",
    gap: "8px",
    width: "min(320px, 36vw)",
    height: "36px",
    paddingInline: "10px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "background",
    color: "muted",
    "@media (max-width: 860px)": {
      width: "100%",
    },
  }),
  searchIcon: css({
    flexShrink: "0",
  }),
  searchInput: css({
    width: "100%",
    minWidth: "0",
    height: "100%",
    padding: "0",
    border: "none",
    outline: "none",
    background: "transparent",
    color: "text",
    fontSize: "0.84rem",
    "&::placeholder": {
      color: "muted",
    },
  }),
  iconButton: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: "0",
    width: "36px",
    height: "36px",
    padding: "0",
    border: "1px solid",
    borderColor: "border",
    borderRadius: "8px",
    backgroundColor: "background",
    color: "text",
    cursor: "pointer",
    transition:
      "background-color 160ms cubic-bezier(0.23, 1, 0.32, 1), border-color 160ms cubic-bezier(0.23, 1, 0.32, 1)",
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "2px",
    },
    "@media (hover: hover) and (pointer: fine)": {
      _hover: {
        borderColor: "accent",
        backgroundColor: "surface",
      },
    },
  }),
  listBody: css({
    flex: "1",
    minHeight: "0",
    overflowY: "auto",
  }),
  loading: css({
    display: "grid",
    alignContent: "start",
    minHeight: "320px",
    padding: "20px",
    color: "muted",
  }),
  error: css({
    display: "grid",
    alignContent: "start",
    minHeight: "320px",
    padding: "20px",
    color: "muted",
  }),
  empty: css({
    display: "grid",
    alignContent: "start",
    minHeight: "220px",
    padding: "20px",
  }),
  messageContent: css({
    display: "grid",
    gap: "8px",
    maxWidth: "30rem",
  }),
  messageTitle: css({
    margin: "0",
    color: "text",
    fontSize: "1.05rem",
    fontWeight: "720",
    lineHeight: "1.25",
  }),
  messageBody: css({
    margin: "0",
    color: "muted",
    fontSize: "0.9rem",
    lineHeight: "1.6",
  }),
  list: css({
    listStyle: "none",
    margin: "0",
    padding: "0",
    "& > li:last-child [data-inbox-row='true']": {
      borderBottom: "none",
    },
  }),
  row: css({
    display: "grid",
    gridTemplateColumns: "28px minmax(0, 1fr) minmax(148px, auto)",
    alignItems: "center",
    gap: "10px",
    minWidth: "0",
    paddingInline: "14px",
    paddingBlock: "10px",
    borderBottom: "1px solid {colors.border}",
    cursor: "pointer",
    outline: "none",
    "@media (hover: hover) and (pointer: fine)": {
      _hover: {
        backgroundColor: "surface",
      },
    },
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "-2px",
    },
    "@media (max-width: 760px)": {
      gridTemplateColumns: "24px minmax(0, 1fr)",
      alignItems: "start",
    },
  }),
  entityIcon: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "24px",
    height: "24px",
    color: "muted",
  }),
  rowMain: css({
    display: "grid",
    gap: "4px",
    minWidth: "0",
  }),
  rowMeta: css({
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: "0",
  }),
  entityLabel: css({
    color: "text",
    fontSize: "0.76rem",
    fontWeight: "700",
    whiteSpace: "nowrap",
  }),
  reasonLabel: css({
    minWidth: "0",
    color: "muted",
    fontSize: "0.76rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  rowCopy: css({
    display: "flex",
    alignItems: "baseline",
    gap: "8px",
    minWidth: "0",
    "@media (max-width: 640px)": {
      display: "grid",
      gap: "2px",
    },
  }),
  rowTitle: css({
    minWidth: "0",
    margin: "0",
    color: "text",
    fontSize: "0.9rem",
    fontWeight: "680",
    lineHeight: "1.35",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  rowDescription: css({
    minWidth: "0",
    margin: "0",
    color: "muted",
    fontSize: "0.84rem",
    lineHeight: "1.35",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  rowState: css({
    display: "grid",
    justifyItems: "end",
    gap: "6px",
    minWidth: "0",
    "@media (max-width: 760px)": {
      gridColumn: "2",
      justifyItems: "start",
    },
  }),
  badgeRow: css({
    display: "flex",
    justifyContent: "flex-end",
    gap: "6px",
    minWidth: "0",
    "@media (max-width: 760px)": {
      justifyContent: "flex-start",
    },
  }),
  statusBadge: css({
    display: "inline-flex",
    alignItems: "center",
    maxWidth: "11ch",
    minHeight: "22px",
    paddingInline: "7px",
    border: "1px solid",
    borderColor: "border",
    borderRadius: "999px",
    backgroundColor: "surface",
    color: "text",
    fontSize: "0.72rem",
    fontWeight: "700",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    "&[data-status='unread']": {
      borderColor: "accent",
      backgroundColor: "background",
    },
  }),
  priorityBadge: css({
    display: "inline-flex",
    alignItems: "center",
    maxWidth: "13ch",
    minHeight: "22px",
    paddingInline: "7px",
    border: "1px solid",
    borderColor: "border",
    borderRadius: "999px",
    color: "muted",
    fontSize: "0.72rem",
    fontWeight: "650",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    "&[data-priority='low']": {
      backgroundColor: "surface",
    },
  }),
  updated: css({
    color: "muted",
    fontSize: "0.76rem",
    whiteSpace: "nowrap",
  }),
  srOnly: css({
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: "0",
    margin: "-1px",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: "0",
  }),
}
