import { css } from "@goddard-ai/styled-system/css"
import { token } from "@goddard-ai/styled-system/tokens"

export default {
  page: css({
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    gap: "14px",
    height: "100%",
    padding: "18px",
  }),
  toolbar: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "14px",
    minWidth: "0",
    padding: "14px 16px",
    borderRadius: "20px",
    border: "1px solid",
    borderColor: "border",
    background: `linear-gradient(180deg, ${token.var("colors.panel")} 0%, ${token.var("colors.surface")} 100%)`,
  }),
  titleGroup: css({
    display: "grid",
    gap: "5px",
    minWidth: "0",
  }),
  title: css({
    minWidth: "0",
    overflow: "hidden",
    color: "text",
    fontSize: "0.96rem",
    fontWeight: "720",
    letterSpacing: "-0.015em",
    lineHeight: "1.2",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  meta: css({
    minWidth: "0",
    overflow: "hidden",
    color: "muted",
    fontFamily: '"IBM Plex Mono", "SFMono-Regular", "Menlo", monospace',
    fontSize: "0.73rem",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  controls: css({
    display: "flex",
    alignItems: "center",
    flex: "0 0 auto",
    gap: "8px",
  }),
  chip: css({
    display: "inline-flex",
    alignItems: "center",
    height: "30px",
    padding: "0 10px",
    borderRadius: "999px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "background",
    color: "muted",
    fontFamily: '"IBM Plex Mono", "SFMono-Regular", "Menlo", monospace',
    fontSize: "0.7rem",
  }),
  button: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    height: "30px",
    padding: "0 11px",
    borderRadius: "999px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "surface",
    color: "text",
    cursor: "default",
    fontSize: "0.73rem",
    fontWeight: "690",
    transition: "background-color 140ms ease, border-color 140ms ease, color 140ms ease",
    _hover: {
      borderColor: "accent",
      backgroundColor: "background",
      color: "accentStrong",
    },
    _disabled: {
      cursor: "not-allowed",
      opacity: 0.55,
    },
  }),
  error: css({
    padding: "10px 14px",
    borderRadius: "16px",
    border: "1px solid",
    borderColor: "danger",
    backgroundColor: `color-mix(in srgb, ${token.var("colors.danger")} 8%, transparent)`,
    color: "danger",
    fontSize: "0.78rem",
    lineHeight: "1.5",
  }),
  viewport: css({
    minHeight: "0",
    height: "100%",
  }),
}
