import { css } from "@goddard-ai/styled-system/css"

export default {
  root: css({
    display: "flex",
    flexDirection: "column",
    minHeight: "100%",
  }),
  header: css({
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "18px",
    flexShrink: "0",
    minWidth: "0",
    paddingBlock: "18px",
    paddingInline: "20px",
    borderBottom: "1px solid",
    borderColor: "border",
    backgroundColor: "background",
    "@media (max-width: 720px)": {
      flexDirection: "column",
    },
  }),
  headerIdentity: css({
    display: "grid",
    gap: "5px",
    minWidth: "0",
  }),
  repository: css({
    margin: "0",
    color: "muted",
    fontFamily: '"SF Mono", "JetBrains Mono", "Menlo", monospace',
    fontSize: "0.75rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  title: css({
    display: "flex",
    alignItems: "center",
    gap: "9px",
    minWidth: "0",
    margin: "0",
    color: "text",
    fontSize: "1rem",
    fontWeight: "720",
    lineHeight: "1.35",
  }),
  description: css({
    margin: "0",
    color: "muted",
    fontSize: "0.9rem",
    lineHeight: "1.6",
  }),
  externalLink: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    flexShrink: "0",
    minHeight: "34px",
    paddingInline: "12px",
    border: "1px solid",
    borderColor: "border",
    borderRadius: "8px",
    backgroundColor: "surface",
    color: "text",
    fontSize: "0.84rem",
    fontWeight: "650",
    textDecoration: "none",
    "@media (hover: hover) and (pointer: fine)": {
      _hover: {
        borderColor: "accent",
        backgroundColor: "background",
      },
    },
  }),
  detailGrid: css({
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "12px",
    padding: "20px",
  }),
  infoCard: css({
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "6px",
    minWidth: "0",
    padding: "14px",
    border: "1px solid",
    borderColor: "border",
    borderRadius: "8px",
    backgroundColor: "surface",
  }),
  infoLabel: css({
    color: "muted",
    fontSize: "0.76rem",
    fontWeight: "700",
  }),
  infoValue: css({
    minWidth: "0",
    color: "text",
    fontSize: "0.88rem",
    lineHeight: "1.45",
    overflowWrap: "anywhere",
  }),
  stateMessage: css({
    display: "grid",
    alignContent: "center",
    justifyItems: "center",
    gap: "10px",
    minHeight: "100%",
    padding: "24px",
    color: "muted",
    textAlign: "center",
  }),
  stateTitle: css({
    color: "text",
    fontSize: "1.02rem",
    fontWeight: "680",
  }),
  stateDescription: css({
    maxWidth: "28rem",
    fontSize: "0.94rem",
    lineHeight: "1.6",
  }),
  stateAction: css({
    marginTop: "4px",
    paddingBlock: "7px",
    paddingInline: "12px",
    border: "1px solid",
    borderColor: "border",
    borderRadius: "6px",
    backgroundColor: "panel",
    color: "text",
    fontSize: "0.9rem",
    fontWeight: "650",
    _hover: {
      backgroundColor: "surface",
    },
  }),
}
