import { css } from "@goddard-ai/styled-system/css"
import { token } from "@goddard-ai/styled-system/tokens"

export default {
  backdrop: css({
    position: "fixed",
    inset: "0",
    backgroundColor: "overlay",
    opacity: "1",
    transition: "opacity 160ms cubic-bezier(0.23, 1, 0.32, 1)",
    zIndex: "50",
    "@starting-style": {
      opacity: "0",
    },
  }),
  positioner: css({
    position: "fixed",
    inset: "0",
    display: "grid",
    justifyItems: "center",
    alignContent: "start",
    padding: "56px 12px 12px",
    zIndex: "51",
  }),
  content: css({
    width: "min(560px, calc(100vw - 24px))",
    maxHeight: "min(480px, calc(100vh - 68px))",
    padding: "0",
    display: "flex",
    flexDirection: "column",
    minHeight: "0",
    border: "1px solid {colors.border}",
    borderRadius: "16px",
    backgroundColor: "panel",
    overflow: "hidden",
    outline: "none",
    opacity: "1",
    transform: "translateY(0)",
    transition:
      "opacity 160ms cubic-bezier(0.23, 1, 0.32, 1), transform 160ms cubic-bezier(0.23, 1, 0.32, 1)",
    "@starting-style": {
      opacity: "0",
      transform: "translateY(8px)",
    },
  }),
  title: css({
    srOnly: true,
  }),
  root: css({
    display: "flex",
    flexDirection: "column",
    minHeight: "0",
    width: "100%",
    background: "transparent",
    color: "text",
  }),
  searchRow: css({
    display: "flex",
    alignItems: "center",
    gap: "10px",
    minHeight: "48px",
    paddingInline: "14px",
    borderBottom: "1px solid {colors.border}",
    borderColor: "border",
  }),
  searchIcon: css({
    flexShrink: "0",
    color: "muted",
  }),
  input: css({
    width: "100%",
    height: "24px",
    border: "none",
    outline: "none",
    backgroundColor: "transparent",
    color: "text",
    fontSize: "0.9rem",
    "&::placeholder": {
      color: "muted",
    },
  }),
  list: css({
    padding: "6px",
    overflowY: "auto",
    "& [data-scope='combobox'][data-part='item']": {
      outline: "none",
    },
    "& [data-scope='combobox'][data-part='item']:focus-visible": {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "-2px",
      borderRadius: "10px",
    },
  }),
  empty: css({
    padding: "20px 14px",
    color: "muted",
    fontSize: "0.88rem",
    textAlign: "center",
  }),
  item: css({
    "--command-palette-icon-color": token.var("colors.muted"),
    display: "grid",
    alignItems: "center",
    gap: "10px",
    width: "100%",
    minHeight: "40px",
    padding: "8px 10px",
    borderRadius: "10px",
    backgroundColor: "transparent",
    color: "text",
    cursor: "pointer",
    "&[aria-selected='true']": {
      "--command-palette-icon-color": token.var("colors.text"),
      backgroundColor: "surface",
    },
  }),
  itemIcon: css({
    display: "inline-flex",
    alignItems: "center",
    color: "var(--command-palette-icon-color)",
  }),
  itemLabel: css({
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "0.9rem",
    fontWeight: "600",
  }),
  shortcut: css({
    paddingInline: "6px",
    minWidth: "0",
    height: "20px",
    borderRadius: "6px",
    border: "1px solid {colors.border}",
    backgroundColor: "background",
    color: "muted",
    fontSize: "0.7rem",
    lineHeight: "18px",
  }),
  itemMeta: css({
    minWidth: "0",
    color: "muted",
    fontSize: "0.75rem",
    fontWeight: "500",
  }),
}
