//! Embeds the drizzle-generated migrations into the binary.
//!
//! `db/migrations/*.sql` is authored by `bun run db:generate` from
//! `db/schema.ts`. This script collects them in filename order and emits a
//! table that `persistence::apply_migrations` applies at startup, so a shipped
//! app never needs the `db` directory on disk.

use std::path::Path;
use std::{env, fs, path::PathBuf, process::Command};

use sha2::{Digest, Sha256};

const PIN: &str = include_str!("whistle-engine.pin");

fn pin(key: &str) -> &'static str {
    PIN.lines()
        .filter_map(|line| line.trim().split_once('='))
        .find_map(|(name, value)| (name == key).then_some(value))
        .expect("whistle-engine.pin missing value")
}

fn main() {
    // Read at run time, not via `env!`: a build-script binary compiled in a
    // session worktree can be reused for this checkout when they share a
    // target dir, and a baked-in path would point at the deleted worktree.
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let repository = Path::new(&manifest_dir).join("../..");
    let directory = repository.join("db/migrations");
    println!("cargo:rerun-if-changed={}", directory.display());

    let mut migrations = fs::read_dir(&directory)
        .unwrap_or_else(|error| panic!("reading {}: {error}", directory.display()))
        .filter_map(Result::ok)
        .filter_map(|entry| {
            let path = entry.path();
            if path.extension()? != "sql" {
                return None;
            }
            let tag = path.file_stem()?.to_str()?.to_owned();
            // drizzle names files `0000_initial_schema`. The prefix is the
            // apply order, so a file without one would sort unpredictably.
            let index: u32 = tag
                .split('_')
                .next()
                .and_then(|prefix| prefix.parse().ok())
                .unwrap_or_else(|| panic!("migration {tag} has no numeric prefix"));
            Some((index, tag, path))
        })
        .collect::<Vec<_>>();
    migrations.sort_by_key(|(index, ..)| *index);

    let mut source = String::from(
        "/// Migrations in apply order, generated by build.rs from db/migrations.\n\
         pub static MIGRATIONS: &[(&str, &str)] = &[\n",
    );
    for (position, (index, tag, path)) in migrations.iter().enumerate() {
        assert_eq!(
            *index as usize, position,
            "migration {tag} breaks the sequence; expected prefix {position:04}"
        );
        let sql = fs::read_to_string(path)
            .unwrap_or_else(|error| panic!("reading {}: {error}", path.display()));
        assert!(!sql.trim().is_empty(), "migration {tag} is empty");
        println!("cargo:rerun-if-changed={}", path.display());
        source.push_str(&format!(
            "    ({tag:?}, include_str!({:?})),\n",
            path.canonicalize().unwrap_or_else(|_| path.clone())
        ));
    }
    source.push_str("];\n");

    let out = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("migrations.rs");
    fs::write(&out, source).unwrap_or_else(|error| panic!("writing {}: {error}", out.display()));

    println!("cargo:rerun-if-changed=whistle-engine.pin");
    println!("cargo:rerun-if-env-changed=WAKU_NEEDLE_LIB_DIR");
    println!("cargo:rustc-check-cfg=cfg(whistle_native)");
    println!("cargo:rustc-check-cfg=cfg(whistle_unavailable)");
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("macos")
        || env::var("CARGO_CFG_TARGET_ARCH").as_deref() != Ok("aarch64")
    {
        println!("cargo:rustc-cfg=whistle_unavailable");
        return;
    }

    println!("cargo:rustc-cfg=whistle_native");
    let out = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo provides OUT_DIR"));
    let archive = env::var_os("WAKU_NEEDLE_LIB_DIR")
        .map(PathBuf::from)
        .map(|dir| dir.join("libneedle.a"))
        .unwrap_or_else(|| out.join("libneedle.a"));
    if !archive.is_file() {
        let url = format!(
            "https://huggingface.co/{}/resolve/{}/{}/libneedle.a",
            pin("repo"),
            pin("commit"),
            pin("platform")
        );
        let partial = archive.with_extension("a.partial");
        fs::create_dir_all(archive.parent().expect("archive path has a parent"))
            .expect("create Needle archive directory");
        let status = Command::new("curl")
            .args([
                "--fail",
                "--silent",
                "--show-error",
                "--location",
                "--proto",
                "=https",
                "--proto-redir",
                "=https",
                "--max-redirs",
                "5",
                "--max-filesize",
                "250000000",
                "--max-time",
                "300",
                "--output",
            ])
            .arg(&partial)
            .arg(&url)
            .status()
            .expect("start curl to fetch pinned Needle archive");
        if !status.success() {
            let _ = fs::remove_file(&partial);
            panic!("failed to fetch pinned Needle archive from {url}");
        }
        fs::rename(partial, &archive).expect("install fetched Needle archive");
    }
    let actual = format!(
        "{:x}",
        Sha256::digest(fs::read(&archive).expect("read Needle archive"))
    );
    assert_eq!(
        actual,
        pin("sha256"),
        "pinned Needle archive SHA-256 mismatch"
    );
    println!(
        "cargo:rustc-link-search=native={}",
        archive.parent().unwrap().display()
    );
    println!("cargo:rustc-link-lib=static=needle");
    println!("cargo:rustc-link-lib=dylib=c++");
}
