import { css } from "@goddard-ai/styled-system/css"

export default {
  root: css({
    display: "grid",
    gridTemplateRows: "auto 1fr",
    height: "100%",
    minWidth: "0",
  }),
  toolbar: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    minHeight: "58px",
    paddingInline: "16px",
    paddingBlock: "10px",
    borderBottom: "1px solid {colors.border}",
  }),
  titleGroup: css({
    minWidth: "0",
  }),
  title: css({
    margin: "0",
    color: "text",
    fontSize: "1rem",
    fontWeight: "720",
    lineHeight: "1.2",
  }),
  subtitle: css({
    margin: "4px 0 0",
    color: "muted",
    fontSize: "0.78rem",
    lineHeight: "1.35",
  }),
  button: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    minHeight: "32px",
    paddingInline: "10px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "background",
    color: "text",
    fontSize: "0.8rem",
    fontWeight: "650",
    cursor: "pointer",
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "2px",
    },
    _disabled: {
      cursor: "not-allowed",
      opacity: 0.58,
    },
  }),
  primaryButton: css({
    borderColor: "accent",
    backgroundColor: "accent",
    color: "accentContrast",
  }),
  body: css({
    display: "grid",
    gridTemplateColumns: "minmax(260px, 380px) minmax(0, 1fr)",
    minHeight: "0",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "1fr",
      overflowY: "auto",
    },
  }),
  pane: css({
    minWidth: "0",
    minHeight: "0",
    padding: "16px",
    borderRight: "1px solid {colors.border}",
    overflowY: "auto",
    "@media (max-width: 900px)": {
      borderRight: "none",
      borderBottom: "1px solid {colors.border}",
    },
  }),
  paneTitle: css({
    margin: "0 0 10px",
    color: "text",
    fontSize: "0.82rem",
    fontWeight: "720",
  }),
  definitionList: css({
    display: "grid",
    gap: "8px",
  }),
  definitionButton: css({
    display: "grid",
    gap: "4px",
    width: "100%",
    padding: "10px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "background",
    color: "text",
    textAlign: "left",
    cursor: "pointer",
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "2px",
    },
    "&[data-selected='true']": {
      borderColor: "accent",
      backgroundColor: "surface",
    },
  }),
  itemTitle: css({
    color: "text",
    fontSize: "0.88rem",
    fontWeight: "700",
    lineHeight: "1.25",
  }),
  itemMeta: css({
    color: "muted",
    fontSize: "0.75rem",
    lineHeight: "1.35",
  }),
  workspace: css({
    minWidth: "0",
    minHeight: "0",
    padding: "16px",
    overflowY: "auto",
  }),
  section: css({
    display: "grid",
    gap: "12px",
    maxWidth: "920px",
  }),
  textArea: css({
    width: "100%",
    minHeight: "180px",
    padding: "10px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "background",
    color: "text",
    fontFamily: "mono",
    fontSize: "0.8rem",
    lineHeight: "1.45",
    resize: "vertical",
  }),
  statusText: css({
    color: "muted",
    fontSize: "0.8rem",
    lineHeight: "1.4",
  }),
  runList: css({
    display: "grid",
    gap: "8px",
  }),
  runButton: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    width: "100%",
    padding: "10px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "background",
    color: "text",
    textAlign: "left",
    cursor: "pointer",
  }),
  badge: css({
    flexShrink: "0",
    paddingInline: "8px",
    paddingBlock: "3px",
    borderRadius: "999px",
    backgroundColor: "surface",
    color: "muted",
    fontSize: "0.72rem",
    fontWeight: "700",
    textTransform: "capitalize",
  }),
  notice: css({
    padding: "12px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "surface",
    color: "muted",
    fontSize: "0.82rem",
    lineHeight: "1.45",
  }),
  error: css({
    color: "danger",
    fontSize: "0.8rem",
    lineHeight: "1.4",
  }),
  actionRow: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
  }),
  runHeader: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "16px",
    borderBottom: "1px solid {colors.border}",
  }),
  runBody: css({
    display: "grid",
    gap: "12px",
    padding: "16px",
  }),
  stepList: css({
    display: "grid",
    gap: "10px",
    maxWidth: "980px",
  }),
  step: css({
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "background",
    overflow: "hidden",
  }),
  stepHeader: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "10px 12px",
    backgroundColor: "surface",
  }),
  stepTitle: css({
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: "0",
    color: "text",
    fontSize: "0.86rem",
    fontWeight: "700",
  }),
  details: css({
    padding: "10px 12px",
    borderTop: "1px solid {colors.border}",
  }),
  summary: css({
    color: "muted",
    fontSize: "0.78rem",
    fontWeight: "650",
    cursor: "pointer",
  }),
  code: css({
    margin: "8px 0 0",
    maxHeight: "260px",
    overflow: "auto",
    padding: "10px",
    borderRadius: "8px",
    backgroundColor: "surface",
    color: "text",
    fontFamily: "mono",
    fontSize: "0.76rem",
    lineHeight: "1.45",
    whiteSpace: "pre-wrap",
  }),
}
