#!/usr/bin/env bun
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, join, posix, relative } from "node:path"
import { fileURLToPath } from "node:url"
import { getErrorMessage } from "radashi"
import ts from "typescript"

const ENTRYPOINTS = ["index.d.ts", "cloudflare/index.d.ts"] as const
const packageDir = dirname(dirname(fileURLToPath(import.meta.url)))
const packageJsonPath = join(packageDir, "package.json")
const outputPath = join(packageDir, "alchemy-typings.d.ts")

type DeclarationFile = {
  path: string
  text: string
}

async function main() {
  const version = await readAlchemyVersion()
  const declarations = await fetchDeclarationGraph(version)
  const content = bundleDeclarations(version, declarations)

  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, content)

  console.log(
    `Wrote ${relative(packageDir, outputPath)} from alchemy@${version} (${declarations.length} files).`,
  )
}

async function readAlchemyVersion() {
  const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8")) as {
    scripts?: Record<string, string>
  }
  const deployScript = packageJson.scripts?.deploy
  const match = deployScript?.match(/\balchemy@([^\s]+)\b/)

  if (!match) {
    throw new Error('package.json#scripts.deploy must contain "alchemy@<version>".')
  }

  return match[1]!
}

async function fetchDeclarationGraph(version: string) {
  const queue = [...ENTRYPOINTS]
  const seen = new Set<string>()
  const declarations: DeclarationFile[] = []

  for (const path of queue) {
    if (seen.has(path)) {
      continue
    }

    seen.add(path)
    const text = await fetchDeclaration(version, path)
    declarations.push({ path, text })

    for (const specifier of getModuleSpecifiers(path, text)) {
      if (!specifier.startsWith(".")) {
        continue
      }

      const resolved = resolveDeclarationPath(path, specifier)

      if (!seen.has(resolved)) {
        queue.push(resolved)
      }
    }
  }

  return declarations
}

async function fetchDeclaration(version: string, path: string) {
  const response = await fetch(`https://unpkg.com/alchemy@${version}/lib/${path}`)

  if (!response.ok) {
    throw new Error(`Failed to fetch ${path}: ${response.status} ${response.statusText}`)
  }

  return response.text()
}

function getModuleSpecifiers(path: string, text: string) {
  const sourceFile = ts.createSourceFile(path, text, ts.ScriptTarget.Latest, true)
  const specifiers: string[] = []

  function visit(node: ts.Node) {
    if (
      (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) &&
      node.moduleSpecifier !== undefined &&
      ts.isStringLiteralLike(node.moduleSpecifier)
    ) {
      specifiers.push(node.moduleSpecifier.text)
    } else if (
      ts.isImportTypeNode(node) &&
      ts.isLiteralTypeNode(node.argument) &&
      ts.isStringLiteralLike(node.argument.literal)
    ) {
      specifiers.push(node.argument.literal.text)
    }

    ts.forEachChild(node, visit)
  }

  visit(sourceFile)
  return specifiers
}

function resolveDeclarationPath(fromPath: string, specifier: string) {
  const fromDir = posix.dirname(fromPath)
  const resolved = posix.normalize(posix.join(fromDir, specifier))

  if (resolved.endsWith(".d.ts")) {
    return resolved
  }

  if (resolved.endsWith(".ts") || resolved.endsWith(".js")) {
    return `${resolved.slice(0, -3)}.d.ts`
  }

  return `${resolved}.d.ts`
}

function bundleDeclarations(version: string, declarations: DeclarationFile[]) {
  const modules = declarations.map(({ path, text }) => {
    return `declare module "${toModuleName(path)}" {\n${indent(rewriteSpecifiers(path, text))}\n}`
  })

  return [
    "// This file is generated by scripts/generate-alchemy-typings.ts.",
    "// oxlint-disable",
    `// Source: alchemy@${version}`,
    "",
    ...modules,
    "",
  ].join("\n")
}

function rewriteSpecifiers(path: string, text: string) {
  const sourceFile = ts.createSourceFile(path, text, ts.ScriptTarget.Latest, true)
  const replacements: { start: number; end: number; text: string }[] = []

  function replaceLiteral(literal: ts.StringLiteralLike) {
    if (!literal.text.startsWith(".")) {
      return
    }

    replacements.push({
      start: literal.getStart(sourceFile) + 1,
      end: literal.getEnd() - 1,
      text: toModuleName(resolveDeclarationPath(path, literal.text)),
    })
  }

  function visit(node: ts.Node) {
    if (
      (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) &&
      node.moduleSpecifier !== undefined &&
      ts.isStringLiteralLike(node.moduleSpecifier)
    ) {
      replaceLiteral(node.moduleSpecifier)
    } else if (
      ts.isImportTypeNode(node) &&
      ts.isLiteralTypeNode(node.argument) &&
      ts.isStringLiteralLike(node.argument.literal)
    ) {
      replaceLiteral(node.argument.literal)
    }

    ts.forEachChild(node, visit)
  }

  visit(sourceFile)

  let output = text
  for (const replacement of replacements.sort((left, right) => right.start - left.start)) {
    output = `${output.slice(0, replacement.start)}${replacement.text}${output.slice(
      replacement.end,
    )}`
  }

  return output.replaceAll(/\/\/# sourceMappingURL=.*$/gm, "").trimEnd()
}

function toModuleName(path: string) {
  if (path === "index.d.ts") {
    return "alchemy"
  }

  if (path === "cloudflare/index.d.ts") {
    return "alchemy/cloudflare"
  }

  return `alchemy/internal/${path.replace(/\.d\.ts$/, "")}`
}

function indent(text: string) {
  return text
    .split("\n")
    .map((line) => (line ? `  ${line}` : ""))
    .join("\n")
}

if (import.meta.main) {
  main().catch((error) => {
    process.stderr.write(`${getErrorMessage(error)}\n`)
    process.exit(1)
  })
}
