/** Internal daemon plugin support contracts for statically composed feature packages. */
import type { HttpRouteTree as BackendRouteTree, RouzerClient } from "@goddard-ai/backend-plugin"
import type { EventEnvelopeFilter, EventEnvelopePropertyFilter } from "@goddard-ai/event-filter"
import { type HttpRouteTree, type RouteRequestHandlerMap } from "@goddard-ai/ipc"
import type { AgentDistribution } from "@goddard-ai/schema/agent-distribution"
import type { KindRegistry, Kindstore, SchemaMigrationPlanner } from "kindstore"
import type { z } from "zod"

import type { UnionToIntersection } from "./type-utils.ts"

/** Named feature extensions exposed by one daemon plugin to plugins that consume it. */
export type FeatureExtensions = Record<string, unknown>

/** Persisted JSON config scopes supported by daemon-owned root config files. */
export type ConfigScope = "user" | "project"

/** Feature-owned config fragment metadata consumed by daemon-owned config substrate. */
export type ConfigDefinition<TRawConfig = unknown, TResolvedConfig = TRawConfig> = {
  readonly schema: z.ZodType<TRawConfig>
  readonly scopes?: readonly ConfigScope[]
  readonly resolve?: (input: {
    readonly user?: TRawConfig
    readonly project?: TRawConfig
  }) => TResolvedConfig | Promise<TResolvedConfig>
}

/** One or more root config namespaces owned by a daemon plugin. */
export type ConfigDefinitions = Record<string, ConfigDefinition<any, any>>

/** Optional routing metadata for event-derived daemon logs. */
export type EventLogMetadata = {
  readonly debug?: string
}

/** Type-only declaration for one in-process daemon plugin event payload. */
export type EventDefinition<TPayload = unknown> = {
  readonly payload?: TPayload
  readonly log?: EventLogMetadata
}

/** One or more event payloads owned by a daemon plugin. */
export type EventDefinitions = Record<string, EventDefinition<any>>

/** Feature-owned handler for backend-originated events delivered by the daemon host stream. */
export type BackendEventHandler<TEvent = unknown> = {
  readonly name: string
  readonly canHandle: (event: unknown) => event is TEvent
  readonly handle: (event: TEvent) => void | Promise<void>
}

export type InferEventPayload<TDefinition> =
  TDefinition extends EventDefinition<infer TPayload> ? TPayload : never

/** Streamable envelope produced whenever one daemon plugin event is emitted. */
export type DaemonEventEnvelope<TName extends string = string, TPayload = unknown> = {
  readonly id: string
  readonly at: string
  readonly name: TName
  readonly payload: TPayload
  readonly log?: EventLogMetadata
}

export type EventEnvelopeUnion<TEvents extends EventDefinitions> = {
  [TName in keyof TEvents & string]: DaemonEventEnvelope<TName, InferEventPayload<TEvents[TName]>>
}[keyof TEvents & string]

export type DaemonEventFilter = EventEnvelopeFilter

export type DaemonEventPropertyFilter = EventEnvelopePropertyFilter

export type DaemonEventSubscriptionEvent = {
  readonly state: "started" | "ended"
  readonly filter: DaemonEventFilter
}

export type EventBus<
  TEmitEvents extends EventDefinitions,
  TListenEvents extends EventDefinitions = TEmitEvents,
> = {
  readonly emit: <TName extends keyof TEmitEvents & string>(
    eventName: TName,
    payload: InferEventPayload<TEmitEvents[TName]>,
  ) => Promise<void>
  readonly on: <TName extends keyof TListenEvents & string>(
    eventName: TName,
    listener: (payload: InferEventPayload<TListenEvents[TName]>) => void | Promise<void>,
  ) => () => void
  readonly observe: (
    listener: (event: EventEnvelopeUnion<TListenEvents>) => void | Promise<void>,
  ) => () => void
  readonly onSubscription: (
    listener: (event: DaemonEventSubscriptionEvent) => void | Promise<void>,
  ) => () => void
  readonly stream: (
    filter: DaemonEventFilter,
    signal: AbortSignal,
  ) => AsyncIterable<EventEnvelopeUnion<TListenEvents>>
}

/** Feature-owned standalone JSON Schema artifact generated by the daemon build. */
export type JsonSchemaArtifactDefinition = {
  readonly name: string
  readonly schema: z.ZodObject<any>
}

/** Feature-owned kindstore schema fragment merged by the daemon composition root. */
export type DbSchemaDefinition = KindRegistry

/** Feature-owned structural kindstore migration applied by the daemon composition root. */
export type DbMigrationDefinition<TSchema extends DbSchemaDefinition = DbSchemaDefinition> = (
  planner: SchemaMigrationPlanner<TSchema>,
) => void

/** Feature-owned kindstore schema and structural migrations. */
export type DbDefinition<TSchema extends DbSchemaDefinition = DbSchemaDefinition> = {
  readonly schema: TSchema
  readonly migrate?: DbMigrationDefinition<TSchema>
}

/** Scoped kindstore surface available to one daemon plugin during setup. */
export type DbContext<TDb extends DbSchemaDefinition> = {
  readonly schema: TDb
  readonly batch: Kindstore<TDb, {}>["batch"]
} & {
  readonly [K in keyof TDb]: Kindstore<TDb, {}>[K]
}

/** One validated merged root-config snapshot made available to daemon plugins. */
export type RootConfigSnapshot<TConfig extends object = Record<string, unknown>> = {
  readonly globalRoot: string
  readonly localRoot: string
  readonly config: TConfig
  readonly version: number
  readonly loadedAt: string
}

/** Narrow config reader exposed to daemon plugins instead of the concrete config manager. */
export type DaemonConfigProvider<TConfig extends object = Record<string, unknown>> = {
  readonly getRootConfig: (cwd?: string) => Promise<RootConfigSnapshot<TConfig>>
  readonly getLastKnownRootConfig: (cwd?: string) => RootConfigSnapshot<TConfig> | null
}

/** Shared daemon logger surface exposed to daemon plugins. */
export type DaemonLogger = {
  readonly log: (event: string, fields?: Record<string, unknown>) => void
  readonly snapshot: () => DaemonLogger
}

/** Structured preview emitted when long text must be truncated for logs. */
export type TextPreview = {
  readonly text: string
  readonly byteLength: number
  readonly truncated: boolean
}

/** Logging and preview helpers exposed to daemon plugins. */
export type DaemonLogService = {
  readonly createLogger: () => DaemonLogger
  readonly createDebug: (
    debugScope: string,
  ) => (event: string, fields?: Record<string, unknown>) => void
  readonly isVerboseLogging: () => boolean
  readonly createPayloadPreview: (
    value: unknown,
    options?: {
      readonly maxStringLength?: number
      readonly parentKey?: string
    },
  ) => unknown
  readonly createChunkPreview: (value: Uint8Array) => TextPreview
}

/** Feature-owned ambient log fields read by daemon logging. */
export type DaemonLogContextDefinition = {
  readonly read: () => Record<string, unknown>
}

/** Stable session metadata carried through live daemon session work. */
export type DaemonSessionContext = {
  sessionId: `ses_${string}`
  acpSessionId: string | null
  cwd: string
  repository: string | null
  prNumber: number | null
  worktreeDir: string | null
  worktreePoweredBy: string | null
}

/** Async log-context runner exposed to daemon plugins that manage sessions. */
export type DaemonSessionContextService = {
  readonly run: <TResult>(context: DaemonSessionContext, callback: () => TResult) => TResult
}

/** Public daemon surface for reading adapter catalog state from the registry cache. */
export type ACPRegistryService = {
  readonly listAdapters: () => Promise<{
    readonly adapters: readonly (AgentDistribution & Record<string, unknown>)[]
    readonly registrySource: "cache" | "fallback"
    readonly lastSuccessfulSyncAt: string | null
    readonly stale: boolean
    readonly lastError: string | null
  }>
  readonly getAdapter: (id: string) => Promise<{
    readonly adapter: AgentDistribution | null
    readonly registrySource: "cache" | "fallback"
    readonly lastSuccessfulSyncAt: string | null
    readonly stale: boolean
    readonly lastError: string | null
  }>
}

/** Builds environment fragments used by daemon-managed agent processes. */
export type DaemonAgentEnvironmentService = {
  readonly createAgentEnvironment: (input: {
    readonly env?: Record<string, string>
  }) => Record<string, string>
}

/** Generic daemon metadata persistence exposed to feature-owned service adapters. */
export type DaemonMetadataStore = {
  readonly get: (key: string) => unknown
  readonly set: (key: string, value: unknown) => void
  readonly delete: (key: string) => void
}

type SetupResult<TPlugin> = TPlugin extends {
  readonly setup?: (...args: any[]) => infer TResult
}
  ? Awaited<TResult>
  : never

/** Extracts the first-class context fields provided by one daemon plugin. */
export type InferProvides<TPlugin> =
  Extract<SetupResult<TPlugin>, { readonly provides: FeatureExtensions }> extends {
    readonly provides: infer TProvides extends FeatureExtensions
  }
    ? TProvides
    : {}

type InferConfigValueFromDefinition<TDefinition> =
  TDefinition extends ConfigDefinition<infer TRaw, infer TResolved>
    ? TDefinition extends { readonly resolve: (...args: any[]) => infer TResolveResult }
      ? Awaited<TResolveResult>
      : unknown extends TResolved
        ? TRaw
        : TResolved
    : unknown

type InferConfigDefinitions<TConfig> =
  TConfig extends Record<string, ConfigDefinition>
    ? {
        readonly [TKey in keyof TConfig]: InferConfigValueFromDefinition<TConfig[TKey]>
      }
    : {}

/** Extracts the resolved config namespace contributed by one daemon plugin. */
export type InferConfig<TPlugin> = TPlugin extends {
  readonly config: infer TConfig extends ConfigDefinitions
}
  ? InferConfigDefinitions<TConfig>
  : {}

type InferDb<TPlugin> = TPlugin extends {
  readonly db: { readonly schema: infer TDb extends DbSchemaDefinition }
}
  ? TDb
  : {}

type InferEvents<TPlugin> = TPlugin extends {
  readonly events: infer TEvents extends EventDefinitions
}
  ? TEvents
  : {}

type InferBackendRoutes<TPlugin> = TPlugin extends {
  readonly backendRoutes: infer TBackendRoutes extends BackendRouteTree
}
  ? TBackendRoutes
  : {}

/** IPC handler map inferred from a plugin Rouzer IPC route tree. */
export type IpcHandlers<TIpcRoutes> = TIpcRoutes extends HttpRouteTree
  ? RouteRequestHandlerMap<TIpcRoutes>
  : never

/** Runtime setup contribution shape used after plugin definitions are erased. */
export type RuntimeSetupContributions = {
  readonly backendEventHandlers?: readonly BackendEventHandler<any>[]
  readonly ipcHandlers?: Record<string, unknown>
  readonly provides?: FeatureExtensions
  readonly close?: () => void | Promise<void>
}

type SetupConfigContext<TConfig> = keyof TConfig extends never ? {} : { readonly config: TConfig }

type SetupDbContext<TDb> = keyof TDb extends never
  ? {}
  : { readonly db: DbContext<Extract<TDb, DbSchemaDefinition>> }

type SetupBackendContext<TBackendRoutes> = keyof TBackendRoutes extends never
  ? {}
  : { readonly backend: RouzerClient<Extract<TBackendRoutes, BackendRouteTree>> }

/** Core daemon runtime substrate available to statically composed daemon plugins. */
export type DaemonSetupSubstrate = {
  readonly daemonRuntime: {
    readonly agentBinDir: string
    readonly idleSessionShutdownTimeoutMs?: number
    readonly getDaemonUrl: () => string
  } & DaemonAgentEnvironmentService
  readonly authTokenStore: {
    readonly set: (token: string) => void | Promise<void>
    readonly delete: () => void | Promise<void>
  }
  readonly log: DaemonLogService
  readonly metadataStore: DaemonMetadataStore
  readonly sessionContext: DaemonSessionContextService
  readonly ipc: {
    readonly requestContext: {
      readonly setSessionId: (id: `ses_${string}`) => void
    }
  }
}

type SetupEventContext<TSelf, TConsumes extends readonly unknown[]> = {
  readonly events: EventBus<
    Extract<InferEvents<TSelf>, EventDefinitions>,
    Extract<UnionToIntersection<InferEvents<TSelf | TConsumes[number]>>, EventDefinitions>
  >
}

/** Infers setup context fields from a plugin's own definition and consumed plugins. */
export type SetupContext<
  TConsumes extends readonly unknown[],
  TSelf = unknown,
> = DaemonSetupSubstrate &
  UnionToIntersection<InferProvides<TConsumes[number]>> & {
    readonly configProvider: DaemonConfigProvider<any>
  } & SetupConfigContext<UnionToIntersection<InferConfig<TSelf | TConsumes[number]>>> &
  SetupDbContext<UnionToIntersection<InferDb<TSelf | TConsumes[number]>>> &
  SetupBackendContext<UnionToIntersection<InferBackendRoutes<TSelf | TConsumes[number]>>> &
  SetupEventContext<TSelf, TConsumes>

/** Daemon plugin shape used to constrain feature plugin values without widening them. */
export type Plugin = {
  /** Stable plugin identifier used for dependency ordering, diagnostics, and owned defaults. */
  readonly name: string
  /** Plugins whose setup contributions are available to this plugin. */
  readonly consumes?: readonly Plugin[]
  /** Root config namespaces owned and resolved by this plugin. */
  readonly config?: ConfigDefinitions
  /** Standalone JSON Schema artifacts generated for plugin-owned config files. */
  readonly jsonSchemas?: readonly JsonSchemaArtifactDefinition[]
  /** In-process daemon events owned and emitted by this plugin. */
  readonly events?: EventDefinitions
  /** Kindstore collections owned by this plugin. */
  readonly db?: DbDefinition
  /** Backend route tree fragment contributed by this plugin. */
  readonly backendRoutes?: BackendRouteTree
  /** IPC route tree fragment contributed by this plugin. */
  readonly ipcRoutes?: HttpRouteTree
  /** Feature-owned ambient log fields contributed to daemon log entries. */
  readonly logContext?: DaemonLogContextDefinition
  /**
   * Runtime hook for handlers, close hooks, and feature extensions.
   *
   * The erased plugin shape accepts any setup context; `definePlugin()` keeps feature authoring exact.
   */
  readonly setup?: (
    context: any,
  ) => void | RuntimeSetupContributions | Promise<void | RuntimeSetupContributions>
}

/** Runtime daemon feature composition produced by static composition roots. */
export type Composition = {
  readonly plugins: readonly Plugin[]
  readonly ipcRoutes: HttpRouteTree
  readonly backendRoutes: BackendRouteTree
  readonly config: Record<string, ConfigDefinition<any, any>>
  readonly jsonSchemas: readonly JsonSchemaArtifactDefinition[]
  readonly events: EventDefinitions
  readonly db: DbDefinition
  readonly logContexts: readonly DaemonLogContextDefinition[]
}
