import { css } from "@goddard-ai/styled-system/css"

export default {
  trigger: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "28px",
    height: "28px",
    padding: "0",
    border: "none",
    borderRadius: "8px",
    backgroundColor: "panel",
    color: "muted",
    cursor: "pointer",
    transition:
      "background-color 180ms cubic-bezier(0.23, 1, 0.32, 1), color 180ms cubic-bezier(0.23, 1, 0.32, 1)",
    _hover: {
      backgroundColor: "surface",
      color: "text",
    },
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accentStrong",
      outlineOffset: "2px",
    },
  }),
  icon: css({
    width: "16px",
    height: "16px",
    color: "inherit",
    borderRadius: "4px",
  }),
  menu: css({
    display: "grid",
    width: "min(320px, var(--available-width))",
    minWidth: "min(260px, var(--available-width))",
    maxWidth: "var(--available-width)",
    maxHeight: "min(340px, var(--available-height))",
    overflow: "hidden",
    border: "1px solid {colors.border}",
    borderRadius: "10px",
    backgroundColor: "panel",
    outline: "none",
    boxShadow: "0 16px 32px rgba(0, 0, 0, 0.18)",
  }),
  list: css({
    display: "grid",
    gap: "0",
    minHeight: "0",
    margin: "0",
    padding: "0",
    overflowY: "auto",
    listStyle: "none",
  }),
  item: css({
    position: "relative",
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    width: "100%",
    minHeight: "34px",
    paddingBlock: "7px",
    paddingInline: "10px",
    border: "none",
    backgroundColor: "transparent",
    color: "text",
    cursor: "pointer",
    fontSize: "0.86rem",
    fontWeight: "560",
    outline: "none",
    textAlign: "left",
    _hover: {
      backgroundColor: "surface",
    },
    _focusVisible: {
      _after: {
        content: '""',
        position: "absolute",
        inset: "2px",
        borderRadius: "8px",
        border: "2px solid {colors.accentStrong}",
        pointerEvents: "none",
      },
    },
    "&[data-active='true']": {
      backgroundColor: "surface",
    },
  }),
  itemBody: css({
    display: "grid",
    gap: "3px",
    minWidth: "0",
  }),
  itemLabel: css({
    minWidth: "0",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    lineHeight: "1.35",
  }),
  itemDetail: css({
    minWidth: "0",
    color: "muted",
    fontSize: "0.76rem",
    fontWeight: "480",
    lineHeight: "1.35",
  }),
}
