import { css } from "@goddard-ai/styled-system/css"
import { token } from "@goddard-ai/styled-system/tokens"

export default {
  root: css({
    display: "flex",
    flexDirection: "column",
    minHeight: "100%",
  }),
  header: css({
    position: "sticky",
    top: "0",
    zIndex: "1",
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "10px",
    flexShrink: "0",
    minWidth: "0",
    borderBottom: "1px solid {colors.border}",
    paddingBlock: "8px",
    paddingInline: "16px",
    backgroundColor: "background",
  }),
  headerIdentity: css({
    display: "flex",
    alignItems: "center",
    flex: "1 1 auto",
    minWidth: "0",
  }),
  headerRepository: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "7px",
    minWidth: "0",
    overflow: "hidden",
    margin: "0",
    color: "muted",
    fontFamily: '"SF Mono", "JetBrains Mono", "Menlo", monospace',
    fontSize: "0.78rem",
    fontWeight: "650",
    lineHeight: "1.2",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    "& svg": {
      flexShrink: "0",
      color: "accentStrong",
    },
  }),
  headerControls: css({
    display: "grid",
    justifyItems: "end",
    gap: "4px",
    flexShrink: "0",
    minWidth: "0",
  }),
  headerActions: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    flexShrink: "0",
  }),
  headerStatusText: css({
    maxWidth: "320px",
    color: "muted",
    fontSize: "0.74rem",
    lineHeight: "1.45",
    textAlign: "right",
  }),
  headerActionButton: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "30px",
    height: "30px",
    border: "1px solid token(colors.border)",
    borderRadius: "6px",
    padding: "0",
    backgroundColor: "surface",
    color: "muted",
    _hover: {
      backgroundColor: "bg.hover",
      color: "text",
    },
    _disabled: {
      cursor: "default",
      opacity: "0.55",
      pointerEvents: "none",
    },
    '&[data-tone="danger"]': {
      color: "danger",
    },
    '&[data-active="true"]': {
      borderColor: "accent",
      backgroundColor: "bg.hover",
      color: "accentStrong",
    },
    "& svg": {
      flexShrink: "0",
      width: "18px",
      height: "18px",
    },
  }),
  headerActionError: css({
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexShrink: "0",
    borderBottom: "1px solid",
    borderColor: "danger",
    paddingBlock: "8px",
    paddingInline: "20px",
    backgroundColor: "surface",
    color: "text",
    fontSize: "0.86rem",
  }),
  headerActionErrorTitle: css({
    color: "danger",
    fontWeight: "700",
    whiteSpace: "nowrap",
  }),
  headerActionErrorDescription: css({
    minWidth: "0",
    overflow: "hidden",
    color: "muted",
    lineHeight: "1.45",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  transcript: css({
    flex: "1 1 auto",
    minHeight: "0",
  }),
  stateMessage: css({
    display: "grid",
    alignContent: "center",
    justifyItems: "center",
    gap: "10px",
    minHeight: "100%",
    padding: "24px",
    color: "muted",
    textAlign: "center",
  }),
  stateTitle: css({
    color: "text",
    fontSize: "1.02rem",
    fontWeight: "680",
  }),
  stateDescription: css({
    maxWidth: "28rem",
    fontSize: "0.94rem",
    lineHeight: "1.6",
  }),
  stateAction: css({
    marginTop: "4px",
    border: "1px solid {colors.border}",
    borderRadius: "6px",
    paddingBlock: "7px",
    paddingInline: "12px",
    backgroundColor: "bg.panel",
    color: "text",
    fontSize: "0.9rem",
    fontWeight: "650",
    _hover: {
      backgroundColor: "bg.hover",
    },
  }),
  composerDock: css({
    position: "sticky",
    bottom: "0",
    zIndex: "1",
    marginTop: "-42px",
    paddingTop: "42px",
    paddingInline: "20px",
    paddingBottom: "20px",
    background: `linear-gradient(to bottom, transparent 0, ${token.var("colors.background")} 42px)`,
    pointerEvents: "none",
    "& > *": {
      pointerEvents: "auto",
    },
  }),
  composerControls: css({
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "start",
    gap: "12px",
  }),
  composerApprovalControl: css({
    marginInlineStart: "auto",
  }),
  composerAgentControl: css({
    display: "inline-grid",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    width: "16px",
    minHeight: "28px",
    color: "text",
    "[data-theme=dark] &": {
      color: "white",
      "& svg": {
        color: "white",
      },
    },
    "& svg": {
      flexShrink: "0",
      color: "muted",
    },
  }),
  composerAgentIcon: css({
    width: "14px",
    height: "14px",
    flexShrink: "0",
    borderRadius: "4px",
    color: "inherit",
  }),
  composerAgentTooltip: css({
    display: "grid",
    gap: "4px",
    alignItems: "center",
    lineHeight: "1.1",
  }),
  composerAgentTooltipVersion: css({
    color: "muted",
    fontSize: "0.72rem",
    fontWeight: "520",
  }),
  composerError: css({
    display: "grid",
    gap: "3px",
    marginBottom: "10px",
    border: "1px solid {colors.danger}",
    borderRadius: "6px",
    paddingBlock: "9px",
    paddingInline: "12px",
    backgroundColor: "surface",
    color: "text",
    fontSize: "0.9rem",
  }),
  composerErrorTitle: css({
    color: "danger",
    fontWeight: "680",
  }),
  composerErrorDescription: css({
    color: "muted",
    lineHeight: "1.45",
  }),
}
