import { css } from "@goddard-ai/styled-system/css"

export default {
  root: css({
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    flexShrink: "0",
  }),
  primaryButton: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "7px",
    minWidth: "0",
    maxWidth: "180px",
    height: "30px",
    border: "1px solid token(colors.border)",
    borderRightWidth: "0",
    borderRadius: "6px 0 0 6px",
    paddingInline: "10px",
    backgroundColor: "surface",
    color: "muted",
    fontSize: "0.78rem",
    fontWeight: "700",
    _hover: {
      backgroundColor: "bg.hover",
      color: "text",
    },
    _disabled: {
      cursor: "default",
      opacity: "0.55",
      pointerEvents: "none",
    },
  }),
  primaryLabel: css({
    minWidth: "0",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  menuButton: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "30px",
    height: "30px",
    border: "1px solid token(colors.border)",
    borderRadius: "0 6px 6px 0",
    backgroundColor: "surface",
    color: "muted",
    _hover: {
      backgroundColor: "bg.hover",
      color: "text",
    },
    _disabled: {
      cursor: "default",
      opacity: "0.55",
      pointerEvents: "none",
    },
  }),
  menu: css({
    minWidth: "220px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    padding: "5px",
    backgroundColor: "bg.panel",
    boxShadow: "lg",
  }),
  menuItem: css({
    display: "grid",
    gridTemplateColumns: "18px minmax(0, 1fr)",
    alignItems: "center",
    gap: "9px",
    width: "100%",
    borderRadius: "5px",
    paddingBlock: "7px",
    paddingInline: "8px",
    color: "text",
    textAlign: "left",
    _hover: {
      backgroundColor: "bg.hover",
    },
    '&[aria-disabled="true"]': {
      opacity: "0.55",
    },
  }),
  menuItemText: css({
    display: "grid",
    gap: "1px",
    minWidth: "0",
  }),
  menuItemName: css({
    overflow: "hidden",
    fontSize: "0.84rem",
    fontWeight: "650",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  menuItemMeta: css({
    overflow: "hidden",
    color: "muted",
    fontSize: "0.72rem",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  error: css({
    maxWidth: "260px",
    marginLeft: "6px",
    overflow: "hidden",
    color: "danger",
    fontSize: "0.78rem",
    fontWeight: "650",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
}
