import { css } from "@goddard-ai/styled-system/css"

export default {
  page: css({
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    height: "100%",
    overflow: "auto",
    padding: "24px",
  }),
  header: css({
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "18px",
  }),
  eyebrow: css({
    color: "accentStrong",
    fontSize: "0.72rem",
    fontWeight: "700",
    textTransform: "uppercase",
  }),
  title: css({
    marginTop: "4px",
    color: "text",
    fontSize: "1.42rem",
    fontWeight: "700",
  }),
  body: css({
    color: "muted",
    lineHeight: "1.62",
  }),
  path: css({
    minWidth: 0,
    color: "muted",
    fontFamily: "mono",
    fontSize: "0.78rem",
    overflowWrap: "anywhere",
  }),
  grid: css({
    display: "grid",
    gridTemplateColumns: "minmax(280px, 1fr) minmax(320px, 1.2fr)",
    gap: "16px",
    paddingBottom: "24px",
    "@media (max-width: 1040px)": {
      gridTemplateColumns: "1fr",
    },
  }),
  panel: css({
    minWidth: 0,
    padding: "18px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "panel",
  }),
  launchPanel: css({
    minWidth: 0,
    padding: "16px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "panel",
  }),
  column: css({
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    minWidth: 0,
  }),
  sectionHeader: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    marginBottom: "14px",
  }),
  sectionTitleRow: css({
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
    color: "text",
  }),
  sectionTitle: css({
    color: "text",
    fontSize: "0.96rem",
    fontWeight: "700",
  }),
  countBadge: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "24px",
    height: "22px",
    paddingInline: "7px",
    borderRadius: "999px",
    backgroundColor: "surface",
    color: "muted",
    fontSize: "0.74rem",
    fontWeight: "700",
  }),
  list: css({
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  }),
  inboxRow: css({
    display: "flex",
    alignItems: "center",
    gap: "12px",
    minWidth: 0,
    padding: "12px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "background",
  }),
  checkoutRow: css({
    display: "flex",
    alignItems: "center",
    gap: "12px",
    minWidth: 0,
    padding: "12px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "background",
  }),
  checkoutHeader: css({
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
  }),
  sessionList: css({
    display: "grid",
    gap: "8px",
  }),
  sessionRow: css({
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
    padding: "10px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "background",
  }),
  sessionButton: css({
    display: "grid",
    gridTemplateColumns: "14px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "9px",
    minWidth: 0,
    flex: "1",
    padding: 0,
    border: 0,
    backgroundColor: "transparent",
    color: "inherit",
    cursor: "pointer",
    textAlign: "left",
  }),
  rowMain: css({
    minWidth: 0,
    flex: "1",
  }),
  rowTitle: css({
    display: "block",
    minWidth: 0,
    color: "text",
    fontSize: "0.88rem",
    fontWeight: "700",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  rowDescription: css({
    minWidth: 0,
    marginTop: "3px",
    color: "muted",
    fontSize: "0.78rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  statusBadge: css({
    flexShrink: 0,
    padding: "4px 7px",
    borderRadius: "999px",
    backgroundColor: "surface",
    color: "muted",
    fontSize: "0.7rem",
    fontWeight: "700",
    textTransform: "capitalize",
    "&[data-status='unread'], &[data-status='changed']": {
      backgroundColor: "surface",
      color: "accentStrong",
    },
    "&[data-status='unavailable']": {
      backgroundColor: "surface",
      color: "danger",
    },
  }),
  statusDot: css({
    width: "8px",
    height: "8px",
    borderRadius: "999px",
    backgroundColor: "muted",
    "&[data-status='active']": {
      backgroundColor: "accentStrong",
    },
    "&[data-status='blocked']": {
      backgroundColor: "text",
    },
    "&[data-status='error']": {
      backgroundColor: "danger",
    },
  }),
  updated: css({
    color: "muted",
    fontSize: "0.74rem",
    whiteSpace: "nowrap",
  }),
  iconButton: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "30px",
    height: "30px",
    flex: "0 0 auto",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "surface",
    color: "muted",
    cursor: "pointer",
    _hover: {
      color: "text",
    },
  }),
  secondaryButton: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "34px",
    marginTop: "12px",
    paddingInline: "12px",
    border: "1px solid {colors.border}",
    borderRadius: "8px",
    backgroundColor: "surface",
    color: "text",
    cursor: "pointer",
    fontWeight: "700",
  }),
  empty: css({
    padding: "18px",
    border: "1px dashed {colors.border}",
    borderRadius: "8px",
    color: "muted",
    fontSize: "0.86rem",
  }),
}
